## ------------------------------------------------------------------------------------------------
context("Check that strings with special characters are properly identified")

test_that("Single strings with special characters are properly identified", {
  expect_equal(has_specials("hello?", white = TRUE), TRUE)
  expect_equal(has_specials("hello?", white = FALSE), TRUE)
  expect_equal(has_specials("hello", white = TRUE), FALSE)
  expect_equal(has_specials("hello", white = FALSE), FALSE)
  expect_equal(has_specials(c("hello", "world!"), white = TRUE), c(FALSE, TRUE))
  expect_equal(has_specials(c("hello", "world!"), white = FALSE), c(FALSE, TRUE))
  expect_equal(has_specials(c("foo.", "fighter"), white = TRUE), c(TRUE, FALSE))
  expect_equal(has_specials(c("foo.", "fighter"), white = FALSE), c(TRUE, FALSE))
  expect_equal(has_specials(c("0<1", "1>0"), white = TRUE), c(TRUE, TRUE))
  expect_equal(has_specials(c("0<1", "1>0"), white = FALSE), c(TRUE, TRUE))
  expect_equal(has_specials(c("\\", "\\\\"), white = TRUE), c(TRUE, TRUE))
  expect_equal(has_specials(c("\\", "\\\\"), white = FALSE), c(TRUE, TRUE))
  expect_equal(has_specials(c("\\\\\\\\", "\\\\\\\\\\", "\\\\\\\\\\\\"), white = TRUE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("\\\\\\\\", "\\\\\\\\\\", "\\\\\\\\\\\\"), white = FALSE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("1|2", "3&4", "5:6"), white = TRUE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("1|2", "3&4", "5:6"), white = FALSE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("7;8", "8^9", "10,11"), white = TRUE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("7;8", "8^9", "10,11"), white = FALSE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("11@12", "13~14", "15`16`"), white = TRUE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("11@12", "13~14", "15`16`"), white = FALSE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("a[1", "2]b", "a(1"), white = TRUE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("a[1", "2]b", "a(1"), white = FALSE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("2)b", "c{1", "2}d"), white = TRUE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("2)b", "c{1", "2}d"), white = FALSE), c(TRUE, TRUE, TRUE))
  expect_equal(has_specials(c("test", "these ", "strings  "), white = TRUE), c(FALSE, TRUE, TRUE))
  expect_equal(has_specials(c("test", "these ", "strings  "), white = FALSE), c(FALSE, FALSE, FALSE))
  expect_equal(has_specials(c("test", "these   ", "strings     "), white = TRUE), c(FALSE, TRUE, TRUE))
  expect_equal(has_specials(c("test", "these   ", "strings     "), white = FALSE), c(FALSE, FALSE, FALSE))
})
